(provide 'shinmera)

;;;;;;
;; Load all.
(require 'shinmera-init)
(require 'shinmera-package)
(require 'shinmera-general)
(require 'shinmera-functions)
;; (require 'shinmera-autocomplete)
(require 'shinmera-company)
;; (require 'shinmera-ecb)
(require 'shinmera-treemacs)
(require 'shinmera-magit)
(require 'shinmera-paste)
(require 'shinmera-windows)
;; (require 'shinmera-uim)
(require 'shinmera-spell)
(require 'shinmera-keys)
(require 'shinmera-gpg)
(require 'shinmera-pass)
(require 'shinmera-mail)
(require 'shinmera-perspective)
(require 'shinmera-purpose)
;; Code
(require 'shinmera-lisp)
;; (require 'shinmera-eiffel)
(require 'shinmera-tex)
(require 'shinmera-web)
;; (require 'shinmera-matlab)
;; (require 'shinmera-haskell)
(require 'shinmera-js)
(require 'shinmera-c)
(require 'shinmera-java)
(require 'shinmera-shell)
(require 'shinmera-markless)
(require 'shinmera-glsl)
;; (require 'shinmera-erlang)
(require 'shinmera-elixir)
(require 'shinmera-arduino)
;; Last
(require 'shinmera-startup)
